/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:9513e82a-eb54-4b54-8be7-c5a4bd1f2ca3",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_EtpSXUXgL",
    "aws_user_pools_web_client_id": "4gfo015cevgsr72ehavai8herj",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "geo": {
        "amazon_location_service": {
            "region": "us-west-2",
            "maps": {
                "items": {
                    "trackerMap-dev": {
                        "style": "VectorEsriStreets"
                    }
                },
                "default": "trackerMap-dev"
            }
        }
    }
};


export default awsmobile;
